### ISSUE TITLE
Breaks App layouts after 1.0.2-canary.2

### ISSUE THREAD

**Issue by clementoriol** [vinissimus/next-translate#464]
I'm using [next-layout](https://github.com/moxystudio/next-layout) for managing my app layouts, and while this was working fine from `1.0.0` to `1.02-canary-1`, after upgrading next-translate to `1.0.2-canary.2` the layouts don't render anymore.

The library uses a HoC to add the layouts, which might cause issues ?
Another guess is that like many layout techniques like [this one](https://adamwathan.me/2019/10/17/persistent-layout-patterns-in-nextjs/) are adding static properties on the exported page function. 

If some other HoC (or maybe what next-translate does with the page) doesn't keep these non-react properties, the layout can't work properly anymore. 

From what I've seen some HoC libraries uses https://github.com/mridgway/hoist-non-react-statics to avoid this issue.

That's all I've got for now :)

**Comment by aralroca** [comment]
@clementoriol Would you share the code of your page to see what next-translate is doing in your case? 🙏 

By the way, there was indeed an issue in canary.2, in [canary.6](https://github.com/vinissimus/next-translate/releases/tag/1.0.2-canary.6) it is fixed, I don't know if it has something to do with it. Does canary.6 work for you?

**Comment by clementoriol** [comment]
@aralroca Just tested and issue persists in canary.6 :( 

I made a [reproduction repo](https://github.com/clementoriol/next-translate-layout-issue) where you can see the issue.


# With canary.6
When you run the dev server and navigate to `/`,  you won't see the layout : 

<img width="1244" alt="Capture d’écran 2021-01-26 à 10 06 10" src="https://user-images.githubusercontent.com/3337108/105824023-268afd00-5fbe-11eb-8ca0-ce38082e2d7d.png">

I'm also noticing that next-translate used `getInitialProps` : 

```
next-translate - compiled page: / - locale: en - namespaces: common, home - used loader: getInitialProps
```

If I console.log the `Component` passed in `_app`, I get a `[Function: AppWithTranslations]`.

# With canary.1
If I downgrade to canary.1, the layout is back : 

<img width="1244" alt="Capture d’écran 2021-01-26 à 10 09 15" src="https://user-images.githubusercontent.com/3337108/105824393-91d4cf00-5fbe-11eb-8a3c-9a41666544ea.png">

This time, next-translate used `getStaticProps` : 
```
next-translate - compiled page: / - locale: en - namespaces: common, home - used loader: getStaticProps
```
And console.logging the Component from `_app` gives me :
```
{ Component:
   { '$$typeof': Symbol(react.forward_ref),
     render: { [Function] displayName: 'WithLayout(Home)' } } }
```
which looks like the what next-layout HoC returns, and what is expected for the layout to be displayed.

**Comment by aralroca** [comment]
@clementoriol Thanks for sharing this. While I'm still investigating, I see that if you manually put an empty `getStaticProps` then it does it right:

![image](https://user-images.githubusercontent.com/13313058/105837841-8dfd7880-5fcf-11eb-9714-67c7bc70fa4e.png)


The problem is with our HOC which is not compatible with moxy's HOC for some reason, I will continue to investigate here. By default when a HOC is detected then Next-translate uses the HOC `appWithI18n` to use `getInitialProps` loader to load the translations by default. This is to comply with this:

> Next-translate ensures that each page only has its namespaces with the current language. So if we have 100 locales, only 1 will be loaded.

> In order to do this we use a **webpack loader** that loads the necessary translation files inside the Next.js methods (**getStaticProps**, **getServerSideProps** or **getInitialProps**). If you have one of these methods already on your page, the webpack loader will use your own method, but the defaults it will use are:
>
> - **`getStaticProps`**. This is the **default method used on most pages**, unless it is a page specified in the next two points. This is for performance, so the calculations are done in build time instead of request time.
> - **`getServerSideProps`**. This is the **default method for dynamic pages** like `[slug].js` or `[...catchall].js`. This is because for these pages it is necessary to define the `getStaticPaths` and there is no knowledge of how the slugs should be for each locale. Likewise, how is it by default, only that you write the getStaticPaths then it will already use the getStaticProps to load the translations.
> -➡️  **`getInitialProps`**. This is the **default method for these pages that use a HoC**. This is in order to avoid conflicts because HoC could overwrite a `getInitialProps`. 
>
> This **whole process is transparent**, so in your pages you can directly consume the `useTranslate` hook to use the namespaces, and you don't need to do anything else.

Reference: https://github.com/vinissimus/next-translate/tree/1.0.1#how-are-translations-loaded

If now the way of loading has changed from canary.1 to canary.2, it is because before the HOC detector we have did not cover so many cases and then it used `getStaticProps` by default (as a mistake). Although in this particular case it works with `getStaticProps`, by default, if there is no loader (`getStaticProps`, `getServerSideProps`...) it should use `getInitialProps` if there is a HOC on the page to avoid possible conflicts. 

However, it remains to fix that our `appWithI18n` HOC is compatible after wrapping the Moxy HOC.

**Comment by clementoriol** [comment]
Thanks @aralroca, it makes perfect sense.

Concerning the compatibility between the `appWithI18n` HoC and moxy's I'd bet on moxys expecting a static `render` attr on the returned component. As I said in the original post, it's a common pattern for persistant layout tricks.
Maybe something like https://github.com/mridgway/hoist-non-react-statics would allow to make sure the `appWithI18n` have these static attributes ?

This could make the library compatible with other libs that uses that kind of trick.

**Comment by aralroca** [comment]
@clementoriol I see that with `hoist-non-react-statics` inside the `appWithI18n` it works correctly, so it is what you say. Thank you! 😊

However, I'm thinking about an alternative to `hoist-non-react-statics`, because that library is already heavier than our HoC.

**Comment by aralroca** [comment]
@clementoriol what do you think about this: 

https://github.com/vinissimus/next-translate/pull/479/files

This way, those who need it can add it to the configuration, and those who don't need it don't need to have these extra KBs. One of the goals of this library is to be tiny and without external dependencies, then I believe that if it is configurable it is better.

**Comment by clementoriol** [comment]
@aralroca Love the approach, makes sense to keep the library lean.
Thank you for addressing this 👍
