### ISSUE TITLE
withNx and next-translate results in duplicate export of '__N_SSG' when using getStaticProps

### ISSUE THREAD

**Issue by amosbastian** [vinissimus/next-translate#677]
## Current Behavior

When using `getStaticProps` on a non-dynamic page (e.g. `index.tsx`) while using `next-translate` with `withNx` it results in the following error:

```
Module parse failed: Duplicate export '__N_SSG' (8:11)
File was processed with these loaders:
 * ../../node_modules/@next/react-refresh-utils/loader.js
 * ../../node_modules/next/dist/build/babel/loader/index.js
 * ../../node_modules/next-translate/lib/cjs/plugin/loader.js
 * ../../node_modules/@next/react-refresh-utils/loader.js
 * ../../node_modules/next/dist/build/babel/loader/index.js
You may need an additional loader to handle the result of these loaders.
| import styles from './index.module.css';
| export var __N_SSG = true;
> export var __N_SSG = true;
| export function Index() {
|   /*
```

and does not load the page, or any the entire app for that matter, at all.

Funnily enough it works fine with a dynamic page, e.g. `[slug].tsx`.

## Expected Behavior

It should be completely fine to use `getStaticProps` while using `next-translate` in a Nx monorepo.

## Steps to Reproduce

I created a minimal GitHub repo where you can reproduce this error: https://github.com/amosbastian/nrwl-repro. I followed https://nx.dev/latest/react/guides/nextjs and simply added `next-translate` and `getStaticProps` to `index.tsx`.

### Failure Logs

As shown above:

```
error - ./pages/index.tsx
Module parse failed: Duplicate export '__N_SSG' (8:11)
File was processed with these loaders:
 * ../../node_modules/@next/react-refresh-utils/loader.js
 * ../../node_modules/next/dist/build/babel/loader/index.js
 * ../../node_modules/next-translate/lib/cjs/plugin/loader.js
 * ../../node_modules/@next/react-refresh-utils/loader.js
 * ../../node_modules/next/dist/build/babel/loader/index.js
You may need an additional loader to handle the result of these loaders.
| import styles from './index.module.css';
| export var __N_SSG = true;
> export var __N_SSG = true;
| export function Index() {
|   /*
getStaticProps
next-translate - compiled page: / - locale: en - namespaces: common - used loader: getStaticProps
Could not find files for / in .next/build-manifest.json
Could not find files for / in .next/build-manifest.json
```

### Environment

```
Node : 14.16.1
OS   : darwin x64
npm  : 7.20.5
```

---

I also created [an issue](https://github.com/nrwl/nx/issues/6904) in the [nrwl/nx repository](https://github.com/nrwl/nx) since I wasn't sure which is causing the error.

**Comment by quyphan97** [comment]
I also had the same problem. do you have a way to fix it? help me

**Comment by aralroca** [comment]
@amosbastian @quyphan97 It should be fixed in [1.1.0-canary.3](https://github.com/vinissimus/next-translate/releases/tag/1.1.0-canary.3) version. I close the issue but it would be nice to know your feedback that now it works without problems. If not, I will reopen the issue.

**Comment by amosbastian** [comment]
It still doesn't work unfortunately 😞

**Comment by shelooks16** [comment]
I experienced the same problem. Playing around for a little I noticed that the error dissapears when changing the way the component and getServerSideProps/getStaticProps are defined.

Produces the error:
```ts
function MyPage() { ... }

export const getServerSideProps = async () => { ... }

export default MyPage;
```

The error vanishes when changing function expression to declaration and vice versa.

Does NOT produce the error:
```ts
const MyPage = () => { ... }

export async function getServerSideProps() { ... }

export default MyPage;
```

**Comment by shelooks16** [comment]
@aralroca unfortunately, `1.1.0-canary.3` does not solve this one. Tested with NX version **12.6.3**

**Comment by aralroca** [comment]
@shelooks16 @amosbastian I've made a fix in the [1.1.0-canary.4](https://github.com/vinissimus/next-translate/releases/tag/1.1.0-canary.4), I hope that with this version it will work. At least @amosbastian with your repo works fine with this version (I have tried to create several pages and several languages too and everything seems to work fine).

**Comment by amosbastian** [comment]
It seems you've fixed it 🙏 thanks! ❤️

**Comment by shelooks16** [comment]
@aralroca although I'm good with above workaround, with `1.1.0-canary.4` the app also fails to build.

Here are some details:
- Nx 12.6.3
- Nextjs 11.0.1
- next-translate 1.1.0-canary.4
- next-translate uses `hoist-non-react-statics`

Error:
```
Failed to compile.

./pages/user/[uid].tsx
Module parse failed: Duplicate export '__N_SSP' (86:11)
File was processed with these loaders:
 * ../../node_modules/next/dist/build/babel/loader/index.js
 * ../../node_modules/next-translate/lib/cjs/plugin/loader.js
 * ../../node_modules/next/dist/build/babel/loader/index.js
You may need an additional loader to handle the result of these loaders.
| PublicUserPage.className = 'bg-milk';
| export var __N_SSP = true;
> export var __N_SSP = true;
| export default PublicUserPage; // @ts-ignore
| // @ts-ignore
```

The page:
```
function PublicUserPage() {
  // ...
}

PublicUserPage.minFullHeight = true;
PublicUserPage.className = 'bg-milk';

export const getServerSideProps = async () => {
  // ...
};

export default PublicUserPage;
```

next.config:
```
const nextConfig = withNx(
  withBundleAnalyzer(
    withNextTranslate({
      webpack: (config, { isServer }) => {
        if (isServer) {
          require('./generate-sitemap-static');
        } else {
          // transpile libraries in node_modules with ES6 to ES5
          config.module.rules.push({
            test: /^(?!.*\.d\.tsx?$).*\.[tj]sx?$/,
            include: [...],
            use: {
              loader: 'babel-loader',
              options: {
                presets: ['@nrwl/next/babel']
              }
            }
          });
        }

        return config;
      }
    })
  )
);

const moduleExports = withSentryConfig(nextConfig, {
  silent: true
});

module.exports = nextConfig;
```

**Comment by aralroca** [comment]
@shelooks16 thanks to report it. It should work well in [1.1.0-canary.5](https://github.com/vinissimus/next-translate/releases/tag/1.1.0-canary.5).  I've applied the same as for the `__N_SSG` to the `__N_SSP`.

**Comment by shelooks16** [comment]
@aralroca I checked out `1.1.0-canary.5`

Now it is good, build goes through 🚀 

Thanks for the fixes 😉 ❤️

**Comment by quyphan97** [comment]
![image](https://user-images.githubusercontent.com/59947963/133915960-03f6d346-d977-4c0f-9d96-e19ef78a145e.png)
![image](https://user-images.githubusercontent.com/59947963/133915979-37991c79-807b-4df6-9ec2-c3bfbbf30d57.png)

@aralroca Is there any way to solve this problem. please just help me

**Comment by aralroca** [comment]
@quyphan97 Next.js does not support "next export" yet for i18n routing. So there is no solution now, we'll have to wait for Next.js to implement it.

**Comment by quyphan97** [comment]
@aralroca sorry. but also thank you

**Comment by quyphan97** [comment]
@aralroca help me! Can you help me check what the error is. I get an error when I refresh the webrower. error occurred while building production. Error occurs when I use getServerSideProps in component
![errror](https://user-images.githubusercontent.com/59947963/147068049-a8f74dba-1139-4b88-9a88-c806572aed0f.png)

**Comment by aralroca** [comment]
No idea @quyphan97. Can you share the code with the reproducible error? Thanks
